### ISSUE TITLE
Documentation: Why not use relative source mapping?

### ISSUE THREAD

**Issue by Milyardo** [ThoughtWorksInc/sbt-scala-js-map#1]
The Scala.js SBT plugin has support for relative source [mappings](https://github.com/scala-js/scala-js/blob/master/sbt-plugin/src/main/scala/scala/scalajs/sbtplugin/ScalaJSPlugin.scala#L199). What problem does this plugin solve that using a source map with a relative path does not?

**Comment by Atry** [comment]
As a library user, I want to debug my application and step into library sources, without cloning the library's source files into my local file system.

Libraries published with this plugin enable the library users to view the source (of correct revision) automatically.

**Comment by Atry** [comment]
Done
