### ISSUE TITLE
a bug 

### ISSUE THREAD

**Issue by timzaak** [ThoughtWorksInc/sbt-scala-js-map#2]
the error info is :
[error] The code base should be cloned from Github, not https://git.oschina.net/XXX/XXX.git
[error](*:scalacOptions) The code base should be cloned from Github, not https://git.oschina.net/XXX/XXXX.git

my dir tree is :

├── .git
├── backend
│   ├── README.md
│   ├── build.sbt
│   ├── logs
│   ├── project
│   ├── src
│   └── target
├── frontend
│   ├── build.sbt
│   ├── project
│   ├── src
│   └── target

**Comment by Atry** [comment]
It's not a bug. 

sbt-scala-js-map is a Sbt plugin that configures source mapping for Scala.js projects hosted on **Github**, not other sites.

See the first paragraph of README

**Comment by timzaak** [comment]
Sorry..
